#!/bin/bash
# Set keyboard layouts
setxkbmap -layout us,hu -option grp:alt_shift_toggle

# Remap Caps Lock to Ctrl when held, Esc when tapped
setxkbmap -option ctrl:nocaps
xcape -e 'Control_L=Escape'
